import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import QuizCard from "./component/QuizCard";

export default function Home() {
  const quiz = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* here */}
        <div className="flex flex-wrap justify-center gap-2 w-[100%] ">
          {quiz.map((item, index) => {
            return <QuizCard />;
          })}
        </div>
      </main>
    </div>
  );
}
